import fs from 'fs';

// Read ORIGINAL IDL generated by anchor build
const idl = JSON.parse(fs.readFileSync('/Users/admin/magicstudio/target/idl/magicstudio.json', 'utf8'));

// Only add metadata.address. Do NOT put address at the root!
idl.metadata = { address: "5nRcojZxaqi3SYd4qBUdD8NzYPEBbWHUkbcHAACY23A2" };

// Write the fixed IDL back
fs.writeFileSync('/Users/admin/magicstudio-frontend/MagicStudio/src/idl/magicstudio.ts', `export const IDL = ${JSON.stringify(idl, null, 2)} as const;\nexport type MagicStudio = typeof IDL;\n`);
console.log("IDL fixed with legacy metadata.address format!");
