import fs from 'fs';
import crypto from 'crypto';

// Read ORIGINAL 0.29.0 IDL generated by anchor build
const idl = JSON.parse(fs.readFileSync('/Users/admin/magicstudio/target/idl/magicstudio.json', 'utf8'));

// 1. Add the program address to the root
idl.address = "5nRcojZxaqi3SYd4qBUdD8NzYPEBbWHUkbcHAACY23A2";

// Helper functions for discriminators
function snakeCase(str) {
    return str.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
}

function getAccountDiscriminator(name) {
    const hash = crypto.createHash('sha256').update(`account:${name}`).digest();
    return Array.from(hash.slice(0, 8));
}

function getInstructionDiscriminator(name) {
    const hash = crypto.createHash('sha256').update(`global:${snakeCase(name)}`).digest();
    return Array.from(hash.slice(0, 8));
}

// 2. Fix program accounts
const canvasStateAccount = idl.accounts?.find(a => a.name === "CanvasState");
if (canvasStateAccount && canvasStateAccount.type) {
    if (!idl.types) idl.types = [];
    idl.types.unshift({
        name: canvasStateAccount.name,
        type: canvasStateAccount.type
    });
    
    idl.accounts = idl.accounts.map(a => ({ 
        name: a.name,
        discriminator: getAccountDiscriminator(a.name)
    }));
}

// 3. Fix instructions
if (idl.instructions) {
    idl.instructions = idl.instructions.map(ix => ({
        ...ix,
        discriminator: getInstructionDiscriminator(ix.name),
        // Fix account mutability/signer fields for 0.30
        accounts: ix.accounts?.map(acc => {
            const newAcc = { ...acc };
            if (newAcc.isMut !== undefined) {
                newAcc.writable = newAcc.isMut;
                delete newAcc.isMut;
            }
            if (newAcc.isSigner !== undefined) {
                newAcc.signer = newAcc.isSigner;
                delete newAcc.isSigner;
            }
            return newAcc;
        })
    }));
}

// 4. Deep traverse and fix `defined: "String"` -> `defined: { name: "String" }`
function fixDefinedTypes(obj) {
    if (Array.isArray(obj)) {
        obj.forEach(fixDefinedTypes);
    } else if (obj !== null && typeof obj === 'object') {
        for (const [key, value] of Object.entries(obj)) {
            if (key === 'defined' && typeof value === 'string') {
                obj[key] = { name: value };
            } else {
                fixDefinedTypes(value);
            }
        }
    }
}

fixDefinedTypes(idl);

// Write the perfectly normalized 0.30+ IDL back
fs.writeFileSync('/Users/admin/magicstudio-frontend/MagicStudio/src/idl/magicstudio.ts', `export const IDL = ${JSON.stringify(idl, null, 2)} as const;\nexport type MagicStudio = typeof IDL;\n`);
console.log("IDL perfectly upgraded to 0.30+ format WITH writable/signer fields!");
