import fs from 'fs';

// Read ORIGINAL 0.29.0 IDL generated by anchor build
const idl = JSON.parse(fs.readFileSync('/Users/admin/magicstudio/target/idl/magicstudio.json', 'utf8'));

// 1. Add the program address to the root
idl.address = "5nRcojZxaqi3SYd4qBUdD8NzYPEBbWHUkbcHAACY23A2";

// 2. Move the account definition from idl.accounts to idl.types
const canvasStateAccount = idl.accounts?.find(a => a.name === "CanvasState");
if (canvasStateAccount && canvasStateAccount.type) {
    if (!idl.types) idl.types = [];
    idl.types.unshift({
        name: canvasStateAccount.name,
        type: canvasStateAccount.type
    });
    
    // Remove inline type from accounts array
    idl.accounts = idl.accounts.map(a => ({ name: a.name }));
}

// 3. Deep traverse and fix `defined: "String"` -> `defined: { name: "String" }`
function fixDefinedTypes(obj) {
    if (Array.isArray(obj)) {
        obj.forEach(fixDefinedTypes);
    } else if (obj !== null && typeof obj === 'object') {
        for (const [key, value] of Object.entries(obj)) {
            if (key === 'defined' && typeof value === 'string') {
                obj[key] = { name: value };
            } else {
                fixDefinedTypes(value);
            }
        }
    }
}

fixDefinedTypes(idl);

// Write the perfectly normalized 0.30+ IDL back
fs.writeFileSync('/Users/admin/magicstudio-frontend/MagicStudio/src/idl/magicstudio.ts', `export const IDL = ${JSON.stringify(idl, null, 2)} as const;\nexport type MagicStudio = typeof IDL;\n`);
console.log("IDL perfectly upgraded to 0.30+ format!");
