[package]
name = "magicstudio"
version = "0.1.0"
description = "MagicCanvas: Real-Time AI Co-Design on Solana using MagicBlock Ephemeral Rollups"
edition = "2021"
rust-version = "1.68.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "magicstudio"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.29.0"
blake3 = "=1.5.0"
zeroize_derive = "=1.4.2"
jobserver = "=0.1.34"
solana-program = "=1.17.0"
serde = "=1.0.204"
proc-macro2 = "=1.0.86"
ryu = "=1.0.18"
typenum = "=1.17.0"
ahash = "=0.8.6"
